### ISSUE TITLE
Incluir a forma de pagamento nos emails 

### ISSUE THREAD

**Issue by hedjho** [anytitleyoulike/praquerumo#14]
Quando o cliente realiza a compra de atividade pelo site recebemos emails informando a compra.

Cartão de Crédito
Passo 1 - Recebemos um email com a confirmação da compra. Nesse email é informado os dados do cliente, atividade/data/sessão, um resumo da compra e o número de voucher.
Ainda falta a informação da forma de pagamento.

Boleto Bancário
Passo 1 - Recebemos um email com a intensão de compra. Estamos tendo bastante dificuldade com o esse email devido a ausência de informações. Atualmente recebemos apenas o nome do cliente.
Precisamos receber também o nome do cliente, atividade/data/sessão, um resumo da compra. O voucher ele virá depois da confirmação da compra no passo 2.

Passo 2 -  Recebemos um email com a confirmação da compra. Nesse email é informado os dados do cliente, atividade/data/sessão, um resumo da compra e o número de voucher.
Ainda falta a informação da forma de pagamento.

**Comment by anytitleyoulike** [comment]
@hedjho quem envia esse email? é o iugu ou o prquerumo?
