### ISSUE TITLE
Excluir o campo comentário da página de detalhes

### ISSUE THREAD

**Issue by hedjho** [anytitleyoulike/praquerumo#18]
Estávamos utilizando um campo "comentário" na página de detalhes da atividade. Precisamos ocultar essa funcionalidade que hoje está sem função e diminuindo a credibilidade do site com a mensagem "Seja o primeiro a comentar sobre sua experiência dessa atividade com o mundo!"

**Comment by matheusbzevedo** [comment]
Finalizado.
