### ISSUE TITLE
Tirar a obrigatoriedade de subir todas as imagens por atividade

### ISSUE THREAD

**Issue by hedjho** [anytitleyoulike/praquerumo#20]
Quando vamos inserir uma atividade no crud é obrigatório fazermos o upload de 5 imagens. Precisamos reduzir para a "Figura de Thumbnail"(que é a figura que vai para a homepage) e também a "Figura 1" que é a primeira imagem da página de detalhes.

A inserção dessas imagens está sendo feita através do crud/atividade.

**Comment by anytitleyoulike** [comment]
#42
