### ISSUE TITLE
Apagar o link map da página (ex. água / aventura / stand up paddle)

### ISSUE THREAD

**Issue by hedjho** [anytitleyoulike/praquerumo#28]

**Comment by anytitleyoulike** [comment]
@hedjho  pode explicar melhor?

**Comment by hedjho** [comment]
Na página de detalhes no canto superior esquerdo existe as informações de elemento, categoria e modalidade ex.: água > aventura > caiaque.

http://www.praquerumo.com.br/atividades/taruma-acu-explorer

Como esses links não possuem ação é melhor excluir temporariamente essas opções.
