### ISSUE TITLE
Diminuir o número do voucher para 6 ou 4 digitios

### ISSUE THREAD

**Issue by hedjho** [anytitleyoulike/praquerumo#30]

**Comment by anytitleyoulike** [comment]
@hedjho descrever melhor

**Comment by hedjho** [comment]
Isso aqui já faz parte também do iugu. 

Quando é realizada uma venda a iugu emite um código de fatura. Esse código estamos utilizando como voucher.

ex.:Voucher 72E1726F936A429AB327FDFE07DF75AC 

Esse voucher é informado num email automático chamado "Pagamento Realizado!", nossa necessidade é diminuir o número desse voucher para 4 ou 6 caracteres.

**Comment by anytitleyoulike** [comment]
@hedjho hmm tem que verifcar se o iugu gera um código menor. pq se só a gente diminuir o tamanho dele, ele vai perder validade

**Comment by hedjho** [comment]
O que você acha de gerarmos um nosso e associarmos ao do iugu?
